---
- name: Install development tools
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - bash-completion
      - build-essential
      - bzip2
      - curl
      - dnsutils
      - gcc
      - g++
      - git
      - htop
      - iftop
      - iputils-ping
      - jq
      - less
      - llvm
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - libxml2-dev
      - libxmlsec1-dev
      - make
      - nano
      - nmon
      - moreutils
      - openssh-client
      - perl
      - rsync
      - tk-dev
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - xz-utils
      - zlib1g-dev
      - zip
  notify:
    - dev-tools installation is done
