---
- name: Install development tools
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - bzip2
      - curl
      - dnsutils
      - gcc
      - g++
      - git
      - htop
      - iftop
      - iputils-ping
      - less
      - nano
      - nmon
      - openssh-client
      - tmux
      - tree
      - unzip
      - vim
      - wget
      - zip
  notify:
    - dev-tools installation is done
