---
- name: Enable SSH Server
  listen: OpenSSH installation is done
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/services.d ]] && mkdir -p /etc/services.d
    mkdir -p /etc/services.d/sshd
    
    cat <<'EOF' > /etc/services.d/sshd/run
    #!/usr/bin/with-contenv bash
    [[ ! -d /run/sshd ]] && mkdir /run/sshd
    /usr/sbin/sshd
    
    EOF
- name: Support loading notebook's environmen variables
  listen: Supported exporting notebook's environment variables
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<EOF

    # Get environment variables from another process
    echo 'set -a; sudo -v > /dev/null 2> /dev/null && eval \$(sudo xargs -0 -L1 -a /proc/1/environ | sed -e "s/=/=\"/;s/$/\"/"); set +a' | cat - ~/.bash_profile > /tmp/bash_profile.tmp
    mv /tmp/bash_profile.tmp ~/.bash_profile

    # Setting static environment variables
    echo 'set -a; source /opt/notebook.env; set +a' | cat - ~/.bash_profile > /tmp/bash_profile.tmp
    mv /tmp/bash_profile.tmp ~/.bash_profile

    EOF