---
- name: Enable SSH Server
  listen: OpenSSH installation is done
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/services.d ]] && mkdir -p /etc/services.d
    mkdir -p /etc/services.d/sshd
    
    cat <<'EOF' > /etc/services.d/sshd/run
    #!/usr/bin/with-contenv bash
    [[ ! -d /run/sshd ]] && mkdir /run/sshd
    /usr/sbin/sshd
    
    EOF