---
- name: Insert CUDA-related paths into .bashrc
  become: false
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    cat <<'EOF' >> ${HOME}/.bashrc
    # CUDA-related settings
    export PATH=/usr/local/cuda/bin:${PATH}
    export LIBRARY_PATH=/usr/local/cuda/lib64/stubs
    export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    EOF