---
- name: Support binding groups
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/cont-init.d ]] && mkdir -p /etc/cont-init.d

    cat <<'EOF' > /etc/cont-init.d/support-binding-groups
    #!/usr/bin/with-contenv bash
    if [[ ! -z "${BIND_GROUPS}" ]]; then
      for group_id in ${BIND_GROUPS//,/ }
      do
        echo "Binding group ${group_id}"
        groupadd --gid ${group_id} group_${group_id}
        usermod -a -G group_${group_id} ${NB_USER}
      done
    fi
    EOF