---
- name: Enable kubectl autocompletion
  listen: kubectl installation is done
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<EOF
    echo 'source <(kubectl completion bash)' >>~/.bashrc
    EOF