---
# Reference: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
- name: Install kubectl.
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    apt update
    apt-get install -y apt-transport-https ca-certificates curl gpg
    [[ ! -d /etc/apt/keyrings/ ]] && mkdir -p /etc/apt/keyrings
    curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
    apt update
    apt install -y kubectl
  notify:
    - kubectl installation is done
- name: Support exporting kubernetes related environment variables
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/cont-init.d ]] && mkdir -p /etc/cont-init.d

    cat <<'EOF' > /etc/cont-init.d/support-exporting-kubernetes-env-vars
    #!/usr/bin/with-contenv bash
    env | grep KUBERNETES_ >> /etc/environment
    EOF
