---
# Reference: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management
- name: Install kubectl.
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    apt update
    apt-get install -y apt-transport-https ca-certificates curl gnupg
    [[ ! -d /etc/apt/keyrings ]] && mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
    chmod 644 /etc/apt/sources.list.d/kubernetes.list 
    apt update
    apt install -y kubectl
  notify:
    - kubectl installation is done
- name: Support exporting kubernetes related environment variables
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/cont-init.d ]] && mkdir -p /etc/cont-init.d

    cat <<'EOF' > /etc/cont-init.d/support-exporting-kubernetes-env-vars
    #!/usr/bin/with-contenv bash
    env | grep KUBERNETES_ >> /etc/environment
    EOF
