- hosts: localhost
  connection: local
  roles:
    - role: takedalab.notebook_images.bashrc
    - role: takedalab.notebook_images.bind_gid
    - role: takedalab.notebook_images.bind_groups
    - role: takedalab.notebook_images.cuda_path
    - role: takedalab.notebook_images.dev_tools
    - role: takedalab.notebook_images.docker_cli
    - role: takedalab.notebook_images.sudo
    - role: takedalab.notebook_images.openssh
    - role: takedalab.notebook_images.kubectl
    - role: takedalab.notebook_images.python
    - role: takedalab.notebook_images.kubeflow_pipeline
    - role: takedalab.notebook_images.pyenv
    - role: takedalab.notebook_images.poetry
    - role: takedalab.notebook_images.nodebrew