---
- name: Install Python
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - python3
      - python3-dev
      - python3-pip
- name: Link python to python3
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -f /usr/bin/python ]] && ln -s /usr/bin/python3 /usr/bin/python