---
# Reference: https://python-poetry.org/docs/
- name: Install poetry
  become: false
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<'EOS'

    curl -sSL https://install.python-poetry.org | python3 -

    echo 'command -v poetry >/dev/null || export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bashrc

    EOS
