---
# Reference: https://python-poetry.org/docs/
- name: Install poetry
  become: false
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<'EOS'

    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

    echo 'command -v poetry >/dev/null || export PATH="${HOME}/.poetry/bin:${PATH}"' >> ~/.bashrc

    EOS