---
- name: Support binding GID
  become: true
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    [[ ! -d /etc/cont-init.d ]] && mkdir -p /etc/cont-init.d

    cat <<'EOF' > /etc/cont-init.d/support-binding-gid
    #!/usr/bin/with-contenv bash
    if [[ ! -z "${BIND_GID}" ]]; then
      echo "Binding GID ${BIND_GID}"
      groupadd --gid ${BIND_GID} group_${BIND_GID}
      usermod -g group_${BIND_GID} ${NB_USER}
    fi
    EOF