---
- name: Prepare .bashrc
  become: false
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<EOS
    cat <<'EOF' >> ${HOME}/.bash_profile
    if [ -f ~/.bashrc ]; then
      . ${HOME}/.bashrc
    fi
    EOF
    
    echo "" >> ${HOME}/.bashrc
    EOS