---
- name: Add GitHub to known-hosts
  listen: dev-tools installation is done
  args:
    executable: /bin/bash
  ansible.builtin.shell: |
    gosu ${NB_USER} bash <<EOF
    mkdir -p ${HOME}/.ssh \
    && ssh-keyscan github.com >> ${HOME}/.ssh/known_hosts
    EOF