name: Build

on:
  push:
    branches:
      - main
      - master
      - develop
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      matrix:
        image:
          - codeserver
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Build image
        env:
          TAG: ${{ github.ref }}
          IMAGE: ${{ matrix.image }}
        shell: bash
        working-directory: ${{ matrix.image }}
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t ghcr.io/takedalab/${IMAGE}:${TAG##*/} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitLab registry
        env:
          TAG: ${{ github.ref }}
          IMAGE: ${{ matrix.image }}
        shell: bash
        run: docker push ghcr.io/takedalab/${IMAGE}:${TAG##*/}
