name: Build

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        base_image:
          - "ubuntu:22.04"
          - "nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04"
          - "nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04"
          - "nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04"
          - "nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04"
          - "nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04"
        playbook:
          - jupyterlab
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          PLAYBOOK: ${{ matrix.playbook }}
          BASE_IMAGE: ${{ matrix.base_image }}
          REF: ${{ github.ref }}
        shell: bash
        working-directory: docker
        run: |
          export BASE_IMAGE=${BASE_IMAGE}
          export IMAGE_TAG=${REF##*/} 
          export PLAYBOOK=${PLAYBOOK}
          export PUSH_IMAGE=true 
          ./build.sh
